name: 'Check Duplicate DMI Icon States'
description: 'Detects that DMIs in folders do not have duplicate icon states'
inputs:
  GITHUB_TOKEN:
    description: A GITHUB_TOKEN to fetch the tool
    required: true
  folders_to_search:
    description: 'Folders to search, comma delineated (default: root folder)'
    required: true
    default: '.'
  flags:
    description: Put other flags for the duplicate checker here
    default: '--warn_read'
  version:
    description: 'Version of the tool to use (default: latest)'
    default: 'v1.0.2'
outputs:
  duplicates:
    description: "Number of duplicate icons as a string"
    value: "0"
runs:
  using: "composite"
  steps:
    - name: Install Duplicate Checker
      uses: jaxxstorm/action-install-gh-release@v1.5.0
      with:
        repo: spacestation13/dmi-duplicate-state-checker
        tag: ${{ inputs.version }}
        cache: enable
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    - run: |
        echo "::set-output name=duplicates::$(./dmi-duplicate-state-checker -p ${{ inputs.folders_to_search }} ${{ inputs.flags }})"
      shell: bash